# Generated by Django 3.0.4 on 2020-04-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('GALLERY', 'Gallery'), ('RESOURCES', 'Resources'), ('DP', 'Discussions and Pages'), ('GENERAL', 'General'), ('BUTTON', 'Button')], default='GENERAL', max_length=128)),
                ('link', models.URLField(blank=True)),
                ('title', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=128)),
            ],
        ),
    ]
