# Generated by Django 3.0.4 on 2020-04-02 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='coordinator',
        ),
    ]
