# Generated by Django 3.0.4 on 2020-05-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='eventactivity',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='eventactivity',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='mealactivity',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='rideactivity',
            name='arrive_time',
        ),
        migrations.RemoveField(
            model_name='rideactivity',
            name='pickup_time',
        ),
        migrations.RemoveField(
            model_name='rideactivity',
            name='pickup_time_buffer',
        ),
        migrations.AlterField(
            model_name='activity',
            name='volunteers_needed',
            field=models.IntegerField(default=0),
        ),
    ]
