# Generated by Django 3.0.4 on 2020-07-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='display_coordinators_on_home_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='community',
            name='home_page_highlight',
            field=models.CharField(choices=[('Calendar', 'Calendar'), ('Family Updates', 'Family Updates'), ('Ways to Help', 'Ways to Help'), ('Message Board', 'Message Board'), ('Photo Gallery', 'Photo Gallery'), ('Well Wishes', 'Well Wishes')], default='Calendar', max_length=28),
        ),
    ]
