# Generated by Django 3.0.4 on 2020-05-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('Giving Rides', 'Giving Rides'), ('Preparing Meals', 'Preparing Meals'), ('Shopping', 'Shopping'), ('Childcare', 'Childcare'), ('Visits', 'Visits'), ('Coverage', 'Coverage'), ('Miscellaneous', 'Miscellaneous'), ('Occasion', 'Occasion')], default='Occasion', max_length=20),
        ),
    ]
