# Generated by Django 3.0.4 on 2020-03-24 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='community',
            name='country',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='community',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='community',
            name='purpose',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='community',
            name='zipcode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='community',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
