# Generated by Django 3.0.4 on 2020-07-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_community_photo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='photo_url',
            new_name='photo_file',
        ),
    ]
