# Generated by Django 3.0.4 on 2020-04-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_community_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='country',
            field=models.CharField(default='US', max_length=128),
        ),
    ]
