# Generated by Django 3.0.4 on 2020-06-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200531_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('Giving Rides', 'Giving Rides'), ('Preparing Meals', 'Preparing Meals'), ('Shopping', 'Shopping'), ('Childcare', 'Childcare'), ('Visits', 'Visits'), ('Coverage', 'Coverage'), ('Miscellaneous', 'Miscellaneous'), ('Occassion', 'Occassion')], default='Occassion', max_length=20),
        ),
    ]
