<<<<<<< HEAD
# Generated by Django 3.0.7 on 2020-10-20 15:26
=======
# Generated by Django 3.0.7 on 2020-10-24 21:25
>>>>>>> d946aef7be63fbdfe315009b1ae8416c310b4edb

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_activity_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_task_reminders',
            field=models.BooleanField(default=True),
        ),
    ]
