# Generated by Django 3.0.4 on 2020-07-05 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200704_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='display_coordinators_on_home_page',
            new_name='display_leaders_on_home_page',
        ),
    ]
