# Generated by Django 3.0.7 on 2020-10-31 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_user_email_task_reminders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='photo_file',
            field=models.FileField(default='https://vignette.wikia.nocookie.net/project-pokemon/images/4/47/Placeholder.png/revision/latest?cb=20170330235552&format=original', max_length=500, upload_to=''),
        ),
    ]
