# Generated by Django 3.0.4 on 2020-04-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200416_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='zipcode',
            field=models.CharField(default='', max_length=10),
        ),
    ]
