# Generated by Django 3.0.4 on 2020-04-02 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200326_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
