# Generated by Django 3.0.4 on 2020-04-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200416_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='address_line_1',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='address_line_2',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='US', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='how_help',
            field=models.CharField(choices=[('INDIVIDUAL', 'As an individual volunteer'), ('HOUSE_OF_WORSHIP', 'Through my house of worship'), ('ORGANIZATION', 'Through a volunteer organization that I am a member of')], default='INDIVIDUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='how_know',
            field=models.CharField(choices=[('FAMILY', 'Family'), ('FRIEND', 'Friend'), ('FRIEND_OF_FRIEND', 'Friend of a friend'), ('COWORKER', 'Coworker'), ('ATTEND_SAME_SCHOOL', 'Attend the same school'), ('NEIGHBOR', 'Neighbor'), ('SOCIAL_MEDIA', 'Social Media'), ('WORSHIP_TOGETHER', 'Worship together'), ('DONT_PERSONALLY', 'Do not personally know')], default='FRIEND', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='how_learn',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number_1',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number_1_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number_2',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number_2_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='skills_to_offer',
            field=models.CharField(choices=[('NO_SELECTION', 'No Selection'), ('CARED_HEALTH_CRISIS', 'Cared for someone with a life-threatening health crisis'), ('HAD_HEALTH_CRISIS', 'I have had a life-threatening health crisis'), ('HEALTHCARE_PROVIDER', 'Healthcare provider'), ('TECH', 'Computer, technology, and social media'), ('FINANCIAL', 'Accounting, financial services'), ('CHILD_CARE', 'Provide licensed child care'), ('LEGAL', 'Legal, attorney'), ('COUNSELING', 'Counseling'), ('HEALTH_INSURANCE', 'Skilled in complex health insurance issues'), ('OTHER', 'Other')], default='NO_SELECTION', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='community',
            name='is_closed',
            field=models.CharField(default='false', max_length=5),
        ),
    ]
