# Generated by Django 3.0.4 on 2020-05-20 21:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200520_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='volunteers_needed',
            new_name='num_volunteers_needed',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='volunteers_signed_up',
        ),
        migrations.AddField(
            model_name='activity',
            name='coordinators',
            field=models.ManyToManyField(related_name='coordinators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='volunteers',
            field=models.ManyToManyField(related_name='volunteers', to=settings.AUTH_USER_MODEL),
        ),
    ]
