# Generated by Django 3.0.4 on 2020-06-02 08:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_wellwish'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='ways_to_help',
            field=tinymce.models.HTMLField(default='hello'),
            preserve_default=False,
        ),
    ]
