# Generated by Django 3.0.4 on 2020-04-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200416_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='is_closed',
            field=models.CharField(default='false', max_length=5),
        ),
    ]
