# Generated by Django 3.0.7 on 2020-11-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20201031_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='day',
            field=models.CharField(default='01', max_length=2),
        ),
        migrations.AddField(
            model_name='photo',
            name='month',
            field=models.CharField(default='01', max_length=2),
        ),
        migrations.AddField(
            model_name='photo',
            name='time',
            field=models.CharField(default='12:00pm', max_length=7),
        ),
        migrations.AddField(
            model_name='photo',
            name='year',
            field=models.CharField(default='2020', max_length=4),
        ),
    ]
