# Generated by Django 3.0.4 on 2020-05-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200424_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='who_help',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='how_help',
            field=models.CharField(choices=[('As an individual volunteer', 'As an individual volunteer'), ('Through my house of worship', 'Through my house of worship'), ('Through a volunteer organization that I am a member of', 'Through a volunteer organization that I am a member of')], default='As an individual volunteer', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='how_know',
            field=models.CharField(choices=[('Family', 'Family'), ('Friend', 'Friend'), ('Friend of a friend', 'Friend of a friend'), ('Coworker', 'Coworker'), ('Attend the same school', 'Attend the same school'), ('Neighbor', 'Neighbor'), ('Social Media', 'Social Media'), ('Worship together', 'Worship together'), ('Do not personally know', 'Do not personally know')], default='Friend', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills_to_offer',
            field=models.CharField(choices=[('No Selection', 'No Selection'), ('Cared for someone with a life-threatening health crisis', 'Cared for someone with a life-threatening health crisis'), ('I have had a life-threatening health crisis', 'I have had a life-threatening health crisis'), ('Healthcare provider', 'Healthcare provider'), ('Computer, technology, and social media', 'Computer, technology, and social media'), ('Accounting, financial services', 'Accounting, financial services'), ('Provide licensed child care', 'Provide licensed child care'), ('Legal, attorney', 'Legal, attorney'), ('Counseling', 'Counseling'), ('Skilled in complex health insurance issues', 'Skilled in complex health insurance issues'), ('Other', 'Other')], default='No Selection', max_length=128),
        ),
    ]
