# Generated by Django 3.0.4 on 2020-05-15 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20200508_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=120)),
                ('date_time', models.CharField(max_length=30)),
                ('show_on_page', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='True', max_length=5)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Community')),
            ],
        ),
    ]
