# Generated by Django 3.0.7 on 2020-11-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20201128_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='month',
            field=models.CharField(default='January', max_length=12),
        ),
    ]
