# Generated by Django 3.0.4 on 2020-08-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityuserrole',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
