# Generated by Django 3.0.7 on 2020-12-09 05:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20201128_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsection',
            name='general_content',
            field=tinymce.models.HTMLField(),
        ),
    ]
